### PR TITLE
Adding inversion operator and a test to verify that it works.

### PR DESCRIPTION
**Pull request by dianakhuang**
An update to https://github.com/excitedleigh/bridgekeeper/pull/10 to add a test to verify that it works as expected.

### CODE REVIEW

**Comment by excitedleigh** [comment]
Sweet, thanks!

**Comment by dianakhuang** [comment]
@excitedleigh not to be too annoying or anything, but is there any chance of getting a new release of `bridgekeeper` with this change in it sometime soon? We'd love to get off our fork and back onto mainline.

**Comment by daisylb** [comment]
I've released 0.8 with this change 👍

**Comment by dianakhuang** [comment]
Thank you!

**Pull request merged**
